baseURL = "https://drinkups.ladevzo.com.com"
languageCode = "en-us"
title = "March Shredz Pushup Challenge"
theme = "typo"


[module]
[module.hugoVersion]
extended = false
min = "0.116.0"

[params]
# Meta description
description = "A Tech Blog"

# Intro on main page, content is markdown
homeIntroTitle = 'Scoreboard!'
homeIntroContent = """
The ratio? Simple: Pushups divided by drinks. Higher is better, unless you're Tank, then it's just terrifying.
Now, get out there and get that ratio so high, even Kevin will be impressed (maybe).
"""

# Collection to display on home
homeCollectionTitle = 'Hot Newz'


# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "posts"
url = "/posts"

[[params.menu]]
name = "about"
url = "/about"